### PR TITLE
Issues 5 and 7 old git repo  and  failing build

### PR DESCRIPTION
**Pull request by mortenwh**
This should close both #5 and #7.

### CODE REVIEW

**Comment by ElodieFZ** [comment]
I can't get the web server to start. The other steps work fine (translating mmd, creating db, ingest records all finish with `done`).
If I check ` http://10.20.30.11`, all I get is 

> This site can’t be reached

Do you have any hints on what to check?

**Comment by mortenwh** [comment]
> I can't get the web server to start. The other steps work fine (translating mmd, creating db, ingest records all finish with `done`).
> If I check ` http://10.20.30.11`, all I get is
> 
> > This site can’t be reached
> 
> Do you have any hints on what to check?

Doesn't this command work?

```
python3 /usr/local/bin/entrypoint.py
```

**Comment by ElodieFZ** [comment]
There is no obvisous error message. I don't get the prompt back, not sure if that's expected.

> pycsw@6e44bb56bd69:~/mmd/bin$ python3 /usr/local/bin/entrypoint.py
DEBUG:__main__:Setting up pycsw's data repository...
DEBUG:__main__:Repository URL: sqlite:////home/pycsw/tests.db
DEBUG:__main__:Launching pycsw with gunicorn --bind=0.0.0.0:8000 --access-logfile=- --error-logfile=- --workers=2 pycsw.wsgi ...
[2020-11-16 13:12:59 +0000] [22] [INFO] Starting gunicorn 20.0.4
[2020-11-16 13:12:59 +0000] [22] [INFO] Listening at: http://0.0.0.0:8000 (22)
[2020-11-16 13:12:59 +0000] [22] [INFO] Using worker: sync
[2020-11-16 13:12:59 +0000] [26] [INFO] Booting worker with pid: 26
[2020-11-16 13:12:59 +0000] [27] [INFO] Booting worker with pid: 27

**Comment by mortenwh** [comment]
Looks good - I get almost the same:

```
pycsw@1b5b7c344a15:~$ python3 /usr/local/bin/entrypoint.py
DEBUG:__main__:Setting up pycsw's data repository...
DEBUG:__main__:Repository URL: sqlite:////home/pycsw/tests.db
DEBUG:__main__:Launching pycsw with gunicorn --bind=0.0.0.0:8000 --access-logfile=- --error-logfile=- --workers=2 pycsw.wsgi ...
[2020-11-16 14:46:41 +0000] [33] [INFO] Starting gunicorn 20.0.4
[2020-11-16 14:46:41 +0000] [33] [INFO] Listening at: http://0.0.0.0:8000 (33)
[2020-11-16 14:46:41 +0000] [33] [INFO] Using worker: sync
[2020-11-16 14:46:41 +0000] [37] [INFO] Booting worker with pid: 37
[2020-11-16 14:46:41 +0000] [38] [INFO] Booting worker with pid: 38
```
Did you then try to go to http://10.20.30.11/ in a browser?

**Comment by mortenwh** [comment]
> There is no obvisous error message. I don't get the prompt back, not sure if that's expected.

That's expected. It's output from the running server.

**Comment by ElodieFZ** [comment]
Yes, I followed the documentation, so the last step described is 

> The csw-catalog-service is now started, and the catalog can be accessed on http://10.20.30.11.

If I open it in a browser (Chrome, Firefox, with and without vpn, in a private window), I get the error message I showed before:
> This site can’t be reached

**Review by ElodieFZ — APPROVED** [review]
The building of VM / docker is functional.

**Comment by ElodieFZ** [comment]
A new issue has been created for the catalog access from a browser (#11).

**Pull request merged**
